"use strict";

const crypto = require("node:crypto");
const Financial = require("./financial");
const BooksBridge = require("./books-bridge");

function money(value) { return Financial.money(value); }
function rows(map) { return Object.keys(map || {}).map((id) => Object.assign({id}, map[id] || {})); }
function stamp(row) { return Number(row && (row.completedAt || row.receivedAt || row.timestamp || row.occurredAt || row.postedAt || row.ts || row.closeAt || row.openAt) || 0); }
function recognized(order) { const status=order && order.status === "Archived" ? order.prevStatus : order && order.status; return !!(order && order.voided !== true && order.paymentStatus !== "pending" && (status === "Completed" || status === "Received")); }
function accountNet(movements, test) { let total=0;(movements||[]).forEach((movement)=>(movement.lines||[]).forEach((line)=>{if(test(String(line.account||""),line,movement))total=money(total+Number(line.debit||0)-Number(line.credit||0));}));return money(total); }
function stable(value) { if(Array.isArray(value))return value.map(stable);if(value&&typeof value==="object"){const out={};Object.keys(value).sort().forEach((key)=>{out[key]=stable(value[key]);});return out;}return value; }
function fingerprint(value) { return crypto.createHash("sha256").update(JSON.stringify(stable(value))).digest("hex"); }
function exception(control,category,sourceId,expected,actual,message,extra) { const difference=money(Number(expected||0)-Number(actual||0)),id=`${control}_${String(sourceId||"close").replace(/[^A-Za-z0-9_-]/g,"_")}`;return Object.assign({id,control,category,sourceId:String(sourceId||""),expected:money(expected),actual:money(actual),difference,message,status:"open",automaticRepairSafe:false},extra||{}); }

function custodyAtCutoff(cashCustody,movements,cutoff) {
  const futureOutflows={};
  (movements||[]).filter((movement)=>stamp(movement)>cutoff).forEach((movement)=>{
    const allocations=movement.custodyAllocations||{};
    const poolReduction=money((movement.lines||[]).reduce((sum,line)=>sum+(line.account==="asset:cash_awaiting_deposit"?Number(line.credit||0)-Number(line.debit||0):0),0));
    if(!(poolReduction>0))return;
    Object.keys(allocations).forEach((id)=>{futureOutflows[id]=money((futureOutflows[id]||0)+Number(allocations[id]||0));});
  });
  return money(rows(cashCustody).reduce((sum,row)=>{
    const created=Number(row.closedAt||row.createdAt||0);
    if(created&&created>cutoff)return sum;
    const laterRecoveries=rows(row.recoveries||{}).filter((recovery)=>Number(recovery.recoveredAt||0)>cutoff).reduce((total,recovery)=>total+Number(recovery.amount||0),0);
    return sum+Number(row.remaining||0)+Number(futureOutflows[row.id]||0)-laterRecoveries;
  },0));
}

function buildClose(input) {
  input=input||{};const closeType=input.closeType==="SHIFT_CLOSE"?"SHIFT_CLOSE":"DAILY_CLOSE",businessDate=String(input.businessDate||""),shiftId=String(input.shiftId||""),cutoff=Number(input.cutoff||Date.now()),shifts=input.shifts||{},allOrders=Object.assign({},input.archivedOrders||{},input.orders||{}),allMovements=rows(input.financialMovements),inventoryMovements=rows(input.inventoryMovements),purchaseInvoices=input.purchaseInvoices||{},booksJournal=input.booksJournal||{},cashCustody=input.cashCustody||{},receivables=input.receivables||{},payables=input.payables||{},platformPayouts=input.platformPayouts||{};
  const shiftDays={};Object.keys(shifts).forEach((id)=>{if(shifts[id]&&shifts[id].openAt)shiftDays[id]=BooksBridge.businessDate(shifts[id].openAt);});
  function orderDay(order){return order&&order.shiftId&&shiftDays[order.shiftId]?shiftDays[order.shiftId]:BooksBridge.businessDate(stamp(order));}
  const authoritativeOrders=rows(allOrders).filter((order)=>recognized(order)&&stamp(order)<=cutoff),authoritativeIds=new Set(authoritativeOrders.map((order)=>order.id));
  const selectedOrders=authoritativeOrders.filter((order)=>orderDay(order)===businessDate&&(closeType!=="SHIFT_CLOSE"||String(order.shiftId||"")===shiftId));
  const selectedIds=new Set(selectedOrders.map((order)=>order.id)),selectedMovements=allMovements.filter((movement)=>stamp(movement)<=cutoff),dayMovements=selectedMovements.filter((movement)=>BooksBridge.businessDate(stamp(movement))===businessDate),exceptions=[],timingItems=[];
  const admin={transactions:selectedOrders.length,grossSales:0,discounts:0,refunds:0,netSales:0,cashSales:0,nonCashSales:0,platformSales:0,expectedCogs:0};
  selectedOrders.forEach((order)=>{const gross=money(order.subtotal!=null?order.subtotal:order.total),discount=money(order.discount),refund=money(order.refundAmount),net=Financial.orderNetSales(order);admin.grossSales=money(admin.grossSales+gross);admin.discounts=money(admin.discounts+discount);admin.refunds=money(admin.refunds+refund);admin.netSales=money(admin.netSales+net);admin.expectedCogs=money(admin.expectedCogs+Number(order.cogsSnapshot||0));const channel=String(order.channel||"instore").toLowerCase(),payments=Array.isArray(order.payments)&&order.payments.length?order.payments:[{method:order.payment,amount:order.total}];if(channel==="grabfood"||channel==="foodpanda")admin.platformSales=money(admin.platformSales+net);else payments.forEach((payment)=>{if(String(payment.method||"").toLowerCase()==="cash")admin.cashSales=money(admin.cashSales+Number(payment.amount||0));else admin.nonCashSales=money(admin.nonCashSales+Number(payment.amount||0));});
    const sourceRows=selectedMovements.filter((movement)=>String(movement.sourceId||"")===order.id&&["order_sale","order_refund","order_void","sales_discount_reclassification","sales_authority_correction"].includes(String(movement.type||""))),actual=Financial.sourceNetSales(sourceRows,order.id),salesPostings=sourceRows.filter((movement)=>movement.type==="order_sale");
    if(!salesPostings.length)exceptions.push(exception("sales_missing","SAFE_REPAIR_AVAILABLE",order.id,net,0,"Completed paid order has no Finance sale movement.",{recommendedAction:"Run deterministic sale posting repair",automaticRepairSafe:true}));
    else if(salesPostings.length>1)exceptions.push(exception("sales_duplicate","ADJUSTMENT_REQUIRED",order.id,1,salesPostings.length,"Order has more than one original Finance sale movement.",{financeMovementIds:salesPostings.map((x)=>x.id)}));
    if(Math.abs(net-actual)>.009)exceptions.push(exception("sales_amount","ADJUSTMENT_REQUIRED",order.id,net,actual,"Admin net sales do not match source-linked Finance revenue.",{financeMovementIds:sourceRows.map((x)=>x.id)}));
    const invRows=inventoryMovements.filter((movement)=>String(movement.sourceId||"")===order.id&&String(movement.type||"")==="sale_usage");if(order.inventoryDeducted!==true&&!invRows.length)exceptions.push(exception("inventory_missing","INVESTIGATION_REQUIRED",order.id,1,0,"Completed order has neither inventory confirmation nor item movements.",{recommendedAction:"Restore exact order inventory movements before adjusting stock"}));else if(order.inventoryDeducted!==true&&invRows.length)exceptions.push(exception("inventory_marker","SAFE_REPAIR_AVAILABLE",order.id,invRows.length,invRows.length,"Inventory movements exist but the confirmation marker is missing.",{recommendedAction:"Verify exact quantities and restore confirmation metadata",automaticRepairSafe:true,itemIds:invRows.map((x)=>x.itemId)}));
    const sourceKeys=Object.keys(booksJournal).filter((key)=>booksJournal[key]&&booksJournal[key].sources&&booksJournal[key].sources[`cogs_${order.id}`]);if(Number(order.cogsSnapshot||0)>0&&!sourceKeys.length)exceptions.push(exception("cogs_missing","SAFE_REPAIR_AVAILABLE",order.id,order.cogsSnapshot,0,"Expected COGS is missing from the Books daily source index.",{recommendedAction:"Rebuild the idempotent Books journal projection",automaticRepairSafe:true}));
  });
  dayMovements.filter((movement)=>["order_sale","order_refund","order_void"].includes(String(movement.type||""))&&!selectedIds.has(String(movement.sourceId||""))).forEach((movement)=>{const sourceId=String(movement.sourceId||"");if(authoritativeIds.has(sourceId))timingItems.push({id:`shift_cutoff_${movement.id}`,control:"sales_cutoff",category:"TIMING_DIFFERENCE",sourceId,amount:money(movement.amount),message:"The sale belongs to a shift business day different from its posting timestamp.",status:"open"});else exceptions.push(exception("sales_orphan","INVESTIGATION_REQUIRED",movement.id,0,movement.amount,"Finance sale movement has no authoritative Admin sale in this close.",{financeMovementIds:[movement.id]}));});
  dayMovements.forEach((movement)=>{const totals=Financial.totals(movement.lines||[]);if(Math.abs(totals.debit-totals.credit)>.009)exceptions.push(exception("unbalanced_movement","SYSTEM_ERROR",movement.id,totals.debit,totals.credit,"Finance movement is not balanced.",{financeMovementIds:[movement.id]}));});
  const finance={netRevenue:money(selectedOrders.reduce((sum,order)=>sum+Financial.sourceNetSales(selectedMovements.filter((movement)=>String(movement.sourceId||"")===order.id),order.id),0)),registerCashMovement:accountNet(dayMovements,(account)=>account==="asset:register_cash"),undepositedBalance:accountNet(selectedMovements,(account)=>account==="asset:cash_awaiting_deposit"),platformReceivables:accountNet(selectedMovements,(account)=>account.indexOf("asset:platform_receivable:")===0),otherReceivables:accountNet(selectedMovements,(account)=>account.indexOf("asset:receivable:")===0),accountsPayable:money(-accountNet(selectedMovements,(account)=>/^liability:(payable|grni|due_to_owner):/.test(account))),customerChangePayable:money(-accountNet(selectedMovements,(account)=>account.indexOf("liability:customer_change_refund:")===0))};
  const openPayables=rows(payables).filter((row)=>row.status==="open"),supplierPayables=openPayables.filter((row)=>row.type!=="customer_change_refund"),customerChangePayables=openPayables.filter((row)=>row.type==="customer_change_refund");
  const subledgers={cashCustody:custodyAtCutoff(cashCustody,allMovements,cutoff),receivables:money(rows(receivables).filter((row)=>row.status==="open").reduce((sum,row)=>sum+Number(row.remainingAmount!=null?row.remainingAmount:row.amount||0),0)),payables:money(supplierPayables.reduce((sum,row)=>sum+Number(row.remainingAmount!=null?row.remainingAmount:row.amount||0),0)),customerChangePayables:money(customerChangePayables.reduce((sum,row)=>sum+Number(row.remainingAmount!=null?row.remainingAmount:row.amount||0),0))};
  if(Math.abs(finance.undepositedBalance-subledgers.cashCustody)>.009)exceptions.push(exception("cash_custody","ADJUSTMENT_REQUIRED","undeposited",finance.undepositedBalance,subledgers.cashCustody,"Undeposited Collection does not agree with physical-cash custody.",{recommendedAction:finance.undepositedBalance>subledgers.cashCustody?"Link the exact existing journal to missing custody":"Review deposits and custody allocations"}));
  if(Math.abs(finance.otherReceivables-subledgers.receivables)>.009)exceptions.push(exception("receivables_control","INVESTIGATION_REQUIRED","receivables",finance.otherReceivables,subledgers.receivables,"Other Receivables control does not agree with its open subledger."));
  if(Math.abs(finance.accountsPayable-subledgers.payables)>.009)exceptions.push(exception("payables_control","INVESTIGATION_REQUIRED","payables",finance.accountsPayable,subledgers.payables,"Accounts Payable control does not agree with open supplier bills."));
  if(Math.abs(finance.customerChangePayable-subledgers.customerChangePayables)>.009)exceptions.push(exception("customer_change_payable_control","INVESTIGATION_REQUIRED","customer_change_refunds",finance.customerChangePayable,subledgers.customerChangePayables,"Customer Change / Refund Payable control does not agree with its open customer obligations."));
  rows(purchaseInvoices).filter((invoice)=>String(invoice.date||"")===businessDate&&!invoice.reversed).forEach((invoice)=>{const ids=Array.isArray(invoice.movementIds)?invoice.movementIds:[];if(!ids.length||ids.some((id)=>!input.financialMovements[id]))exceptions.push(exception("purchase_posting","SAFE_REPAIR_AVAILABLE",invoice.id,invoice.total,0,"Purchase is missing one or more linked Finance movements.",{recommendedAction:"Repair from the authoritative purchase record; do not post a manual inventory journal",automaticRepairSafe:true}));});
  rows(platformPayouts).filter((payout)=>!payout.reversed&&!payout.depositMovementId&&Number(payout.actualPayout)>0).forEach((payout)=>timingItems.push({id:`platform_payout_${payout.id}`,control:"platform_settlement",category:"TIMING_DIFFERENCE",sourceId:payout.id,amount:money(payout.actualPayout),message:"Platform payout is recorded but has not yet reached its configured destination account.",status:"open"}));
  const selectedShifts=rows(shifts).filter((shift)=>shiftDays[shift.id]===businessDate&&(closeType!=="SHIFT_CLOSE"||shift.id===shiftId));selectedShifts.forEach((shift)=>{if(shift.status!=="closed")exceptions.push(exception("shift_open","PERIOD_CUTOFF_DIFFERENCE",shift.id,1,0,"Shift remains open at the close cutoff."));if(shift.status==="closed"&&Math.abs(Number(shift.variance||0))>.009&&!String(shift.varianceStatus||"").match(/reviewed|resolved|reconciled/))exceptions.push(exception("cash_variance","INVESTIGATION_REQUIRED",shift.id,0,shift.variance,"Shift cash difference remains unresolved.",{recommendedAction:"Resolve the linked Admin variance and Finance control account together"}));});
  const blocking=exceptions.filter((item)=>item.category!=="TIMING_DIFFERENCE"),status=blocking.length?"EXCEPTIONS_OPEN":timingItems.length?"RECONCILED_WITH_TIMING_ITEMS":"RECONCILED",controlTotals={salesDifference:money(admin.netSales-finance.netRevenue),cashCustodyDifference:money(finance.undepositedBalance-subledgers.cashCustody),receivablesDifference:money(finance.otherReceivables-subledgers.receivables),payablesDifference:money(finance.accountsPayable-subledgers.payables),customerChangePayablesDifference:money(finance.customerChangePayable-subledgers.customerChangePayables)};
  const result={schemaVersion:1,reconciliationVersion:2,closeType,businessDate,shiftId:closeType==="SHIFT_CLOSE"?shiftId:"",cutoff,timezone:"Asia/Manila",status,admin,finance,subledgers,controlTotals,transactionCount:selectedOrders.length,shiftIds:selectedShifts.map((x)=>x.id),exceptions,timingItems,repairSummary:{safeRepairCount:exceptions.filter((x)=>x.automaticRepairSafe).length,repairsPerformed:[]}};result.snapshotHash=fingerprint(result);return result;
}

module.exports={buildClose,fingerprint,recognized};
